import Head from 'next/head'
import TotalStats from '../../components/totalStats/TotalStats'
import BotTable from '../../components/botTable/BotTable'

export default function Home() {
  return (
    <>
      <Head>
        <title>Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Oswald:wght@500&display=swap" rel="stylesheet"/>
      </Head>

      <main>
       <TotalStats/>
        <BotTable/>
      </main>

     
      </>
  )
}


