import Head from 'next/head'
import TotalStats from '../../components/totalStats/TotalStats'
import BotTable from '../../components/botTable/BotTable'

export default function Home() {
  return (
    <>
      <Head>
        <title>Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <TotalStats/>
        <BotTable/>
      </main>

     
      </>
  )
}


