import s from '../styles/Home.module.scss'
import BotList from '../components/botList/BotList'
import BotFilter from '../components/botFilter/BotFilter'
import { useGetAllStatsQuery } from '../slices/apiSlice';
import SpinnerText from '../components/spinner/SpinnerText';
import Head from 'next/head';



export default function Home() {
    function numberWithSpaces(x) {
        return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
    }

    const {data: money, isLoading, isSuccess} = useGetAllStatsQuery()

    return (
        <>
        <Head>
            <title>Bots</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={s.container}>
            <main>
                <div className={s.middle__section}>
                    <div className={s.total__money}>
                        <img className={s.total__img} src='/assets/money.svg' alt="" />
                        <h1 className={s.total__digits}>{isLoading ? <SpinnerText/> : numberWithSpaces(money.totalDep)} $</h1>
                    </div>
                    <BotFilter/>
                </div>
                <BotList/>
            </main>
        </div>
        </>
    )
}
